### ISSUE TITLE
1.0 Release tracker

### ISSUE THREAD

**Issue by Relintai** [Relintai/voxelman#1]
This issue tracks the things that needs to be done for the first stable release.

- [ ] Port everything from Broken Seals (transvoxel mesher implementation for example, VoxelWorld has quite a few things there, etc).
- [x] Rename the current transvoxel mesher, because of smaller changes. E.g. The tables are modified, to support standard uv mapping.
- [x] Add the original transvoxel tables as well.
- [x] Organize meshers into folders.
- [ ] Ability to exclude meshers at compile time.
- [x] Fix multithreaded generation.
- [ ] Finish clutter support. (Grass for example)
- [ ] Liquid meshing support. (Static for now).
- [ ] Clean up things that are no longer needed.
- [ ] Documentation (Sphinx)
- [ ] Class docs (XML) - At least the things that are not self explanatory.
- [x] Make sure, that dependencies to my other modules optional.
- [x] VoxelChunk's, and VoxelMesher's api will probably need some cleanups.
- [x] Updateable, and scriptable block support for things like crops, or in world effects.

I'm doing these as part of an assignment (I'm really glad that they let me), so these will be done in about 1-2 months.

- [x] Chunk serialization, and deserialization.
- [x] Make sure something is available to compress chunk data.
- [x] Editor tools for in-editor voxel editing. Think of GridMap. It should support fill values as well.
- [x] Simple Minecraft-like voxel mesher.

**Comment by Relintai** [comment]
Not as clear cut.
